# Generated by Django 3.0.5 on 2020-07-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='stie_name',
            new_name='site_name',
        ),
    ]
