# Generated by Django 3.0.5 on 2020-07-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20200730_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='pavicon',
            field=models.ImageField(null=True, upload_to='pavi'),
        ),
    ]
