# Generated by Django 3.0.5 on 2020-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_auto_20200730_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favi'),
        ),
    ]
