# Generated by Django 3.0.5 on 2020-06-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='./static/IU.jpg', upload_to='pofolimages'),
        ),
    ]
