# Generated by Django 3.0.5 on 2020-07-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='mapPoint',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
